#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

INTERNAL_MONITOR="eDP1"
EXTERNAL_MONITOR="DP1"
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep -w "${EXTERNAL_MONITOR} connected") ]]; then
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 10
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi

bspc config border_width 3
bspc config window_gap 4
bspc config normal_border_color '#d3d3d3'
bspc config active_border_color '#d3d3d3'

bspc config top_padding 32

bspc config split_ratio 0.7
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color '#571D3F'
#bspc config focused_border_width 10

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# AUTOSTART
# Helper function to check for active process, if not found starts program on the background
_run() {
    if ! pgrep -x "${1}" &>/dev/null; then
        "$@" &
    fi
}

monitor_add() {
  # Move last 5 desktops to external monitor
  for desktop in $(bspc query -D --names -m "$INTERNAL_MONITOR" | tac | sed 5q | tac); do
    bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR"
  done

  # Remove default desktop created by bspwm
  bspc desktop Desktop --remove

  # reorder monitors
  bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
}

monitor_remove() {
  # Add default temp desktop because a minimum of one desktop is required per monitor
  bspc monitor "${EXTERNAL_MONITOR}" -a Desktop

  # Move all desktops except the last default desktop to internal monitor
  for desktop in $(bspc query -D -m "${EXTERNAL_MONITOR}");	do
    bspc desktop "$desktop" --to-monitor "${INTERNAL_MONITOR}"
  done

  # delete default desktops
  bspc desktop Desktop --remove

  # reorder desktops
  bspc monitor "$INTERNAL_MONITOR" -o 1 2 3 4 5 6 7 8 9 10
}

#setup background
feh --bg-scale ~/Pictures/Wales.jpg

_run picom --backend glx

# Kill and relaunch polybar
killall -q polybar
while pgrep -u $UID -x polybar > /dev/null; do sleep 2; done
if [[ $(xrandr -q | grep -w "${EXTERNAL_MONITOR} connected") ]]; then
  polybar --reload primary -c ~/.config/polybar/config.ini </dev/null >/var/tmp/polybar-primary.log 2>&1 200>&- &
  polybar --reload secondary -c ~/.config/polybar/config.ini </dev/null >/var/tmp/polybar-secondary.log 2>&1 200>&- &
else
  polybar --reload primary -c ~/.config/polybar/config.ini </dev/null >/var/tmp/polybar-primary.log 2>&1 200>&- &
fi



if [[ $(xrandr -q | grep -w "${EXTERNAL_MONITOR} connected") ]]; then

	# Get available resolutions and find the highest one
	MAX_RES=$(xrandr | grep -A1 "^${EXTERNAL_MONITOR} connected" | tail -n +2 | awk '{print $1}' | sort -nr | head -n1)
	# Parse width and height
	MAX_WIDTH=$(echo $MAX_RES | cut -d'x' -f1)
	MAX_HEIGHT=$(echo $MAX_RES | cut -d'x' -f2)
	# Set cap resolution
	CAP_WIDTH=2560
	CAP_HEIGHT=1440
	# Compare and set resolution
	if [ "$MAX_WIDTH" -gt "$CAP_WIDTH" ] || [ "$MAX_HEIGHT" -gt "$CAP_HEIGHT" ]; then
		res="${CAP_WIDTH}x${CAP_HEIGHT}"
	else
		res="$MAX_RES"
	fi

  # set xrandr rules for docked setup
  xrandr --output "${INTERNAL_MONITOR}" --mode 1920x1080 --rotate normal --output "${EXTERNAL_MONITOR}" --primary --mode $res --rotate normal --left-of "${INTERNAL_MONITOR}"
  if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 5 ]]; then
    monitor_add
  fi
  bspc wm -O "${INTERNAL_MONITOR}" "${EXTERNAL_MONITOR}"
else
  # set xrandr rules for mobile setup
  xrandr --output "${INTERNAL_MONITOR}" --primary --mode 1920x1080 --rotate normal --output "${EXTERNAL_MONITOR}" --off
  if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 10 ]]; then
    monitor_remove
  fi
fi

##turn off screen timeout
xset -dpms s off

#restart sxhkd
pkill -USR1 -x sxhkd

# start xscreensaver
xscreensaver --no-splash &

#load info workspace
#bspc rule -a kitty desktop=^10 state=tiled follow=true

# calibrate touchscreen to only the laptop screen
xinput map-to-output 'ELAN2097:00 04F3:2502' eDP1

# increase contrast and brightness
xrandr --output $INTERNAL_MONITOR --brightness 1.1 --gamma 0.90
